[WIP] #159361717 Products Review and Rating
andela/ET-rc pull request #15
Opened 2018-08-23 10:17 UTC by bekomay26

#### What does this PR do?
- Adds customer reviews and ratings for shops.

#### Description of Task to be completed?
Customers should be able to rate and review a  store. When a user visits a store page, the user should be able to rate the store and add a review of the store

#### How should this be manually tested?
Navigate to the store page and click on the View reviews button

#### What are the relevant pivotal tracker stories?
159738422

#### Any background context you want to add?
N/A

2018-08-23 12:43 UTC, Nkemjiks commented
Hi @bekomay26 and @Hasstrup, please include a complete screenshot of the whole page so we can see the shop as well. Also do well to resolve all hound issues.

2018-08-23 12:44 UTC, Nkemjiks requested changes
Please check the comment and respond accordingly

2018-08-24 09:54 UTC, bekomay26 commented
@Nkemjiks Thanks for the review, I have changed the screenshots and I am fixing the hound issues.

2018-08-24 10:17 UTC, bekomay26 commented on imports/plugins/custom/shop-review/server/publications/review.js
> +Meteor.publish("shop.reviews", function (shopId) {
Meteor publication doesn't work properly with arrow functions

2018-08-24 14:04 UTC, bekomay26 commented
@Nkemjiks I have fixed the hound issues

2018-08-24 18:23 UTC, kenware commented
Nice work @bekomay26 and @Hasstrup,  however, it will be better if the list of reviews is paginated instead of loading all to the client. Checkout react-easy-pagination component for pagination

2018-08-24 18:30 UTC, bekomay26 commented
Thank you for the review @kenware, we will endeavour to implement the feature. Also, thanks for the recommendation, it will make our work a tad bit easier.

2018-08-27 09:24 UTC, Nkemjiks approved these changes

2018-08-27 09:35 UTC, Onnassiz approved these changes
Nice job @kenware and @ikenjoku. Keep it up.

2018-08-28 08:17 UTC, closed without merging