Ft digital products 159361724
andela/ET-rc pull request #18
Opened 2018-08-30 09:26 UTC by Nkemjiks

#### What does this PR do?
Adds a feature that allows vendors to add and sell digital products like ebooks, songs etc.

#### Description of Task to be completed?
A vendor should be able to sell digital goods like music and e-books independently, or mixed with physical goods.

#### How should this be manually tested?
Visit . Login as an admin, try adding a digital product. Then view the digital products on the landing page. You can also buy a digital product to see the link in your email.

#### What are the relevant pivotal tracker stories?
[#159361724](https://www.pivotaltracker.com/story/show/159361724)

#### Any background context you want to add?
N/A

#### Screenshots
<img width="1439" alt="screen shot 2018-08-30 at 10 15 30 am" src="https://user-images.githubusercontent.com/32465536/44842838-ca7dec00-ac3e-11e8-99bb-34679a21451e.png">
<img width="1440" alt="screen shot 2018-08-30 at 10 15 55 am" src="https://user-images.githubusercontent.com/32465536/44842839-ca7dec00-ac3e-11e8-9d3d-c1884ce992de.png">
<img width="1440" alt="screen shot 2018-08-30 at 10 16 08 am" src="https://user-images.githubusercontent.com/32465536/44842840-cb168280-ac3e-11e8-929c-4441e029324b.png">
<img width="884" alt="screen shot 2018-08-30 at 10 16 35 am" src="https://user-images.githubusercontent.com/32465536/44842841-cb168280-ac3e-11e8-956c-ca35c7957834.png">

2018-08-30 17:47 UTC, adetola-ralph requested changes

2018-08-30 17:47 UTC, adetola-ralph commented on imports/plugins/custom/digital-products/client/components/productKind.js
> +        Logger.error("Fetching product failed");
Add a return so that the function breaks execution here

2018-08-30 18:04 UTC, Nkemjiks commented on imports/plugins/custom/digital-products/client/components/productKind.js
> +        Logger.error("Fetching product failed");
Noted @adetola-ralph

2018-08-31 00:17 UTC, dikaeinstein approved these changes
Good Job @Nkemjiks, I'm particularly impressed with the way your react components are well structured and how clean your code is. But there is room for improvements like using shorthand es6 object property names.

2018-08-31 05:28 UTC, adetola-ralph approved these changes

2018-08-31 05:28 UTC, merged